import {IProduct} from "../interfaces/IProduct";
import * as mongoose from "mongoose";
import {Status} from "../enums/status";

const Schema = mongoose.Schema;
const ProductSchema = new Schema(
    {
        name:{
            type:String,
            required:true,
            trim:true
        },
        shortDescription:{
            type:String,
            require:false,
            trim:true,
        },
        description:{
            type:String,
            require:false,
            trim:true,
        },
        categories:[{type:Schema.Types.ObjectId,required:false,ref:'category'}],
        brands:[{type:Schema.Types.ObjectId,required:false,ref:'brands'}],
        images:[String],
        tags:[{type:Schema.Types.ObjectId,required:false,ref:'tags'}],
        price:{
            type:Number,
            required:true,
            trim:true
        },
        costPrice:{
            type:Number,
            default:0,
            required:false,
            trim:true
        },
        comparePrice:{
            type:Number,
            default:0,
            required:false,
            trim:true
        },
        discount:{
            type:Number,
            default:0,
            required:false,
            trim:true
        },
        qty:{
            type:Number,
            required:true,
            trim:true
        },
        status:{
            type:String,
            required:true,
            enum:[Status.active,Status.inactive],
            default:Status.active,
            trim:true
        },
        sku:{
            type:String,
            required:true,
            unique:true,
            trim:true
        },
        sellWhenOutOfStock:{
            type:Boolean,
            default:false
        },
        variants:[
            {
                option:{
                    type:String,
                    trim:true
                },
                choices:{
                    type:[String],
                    trim:true
                }
            }
            ],
    }
);
export default mongoose.model<IProduct & mongoose.Document>('products',ProductSchema)